# Generated by Django 6.1 on 2026-08-29 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('club', models.CharField(blank=True, max_length=200)),
                ('belt', models.CharField(blank=True, max_length=64)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('role', models.CharField(choices=[('trainer', 'Тренер'), ('parent', 'Родитель'), ('secretary', 'Секретарь'), ('admin', 'Администратор')], default='parent', max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
