# Generated by Django 6.1 on 2026-08-29 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tatami',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('order', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField()),
                ('mats_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('published', 'Опубликован'), ('finished', 'Завершён')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gender', models.CharField(choices=[('male', 'Мальчик'), ('female', 'Девочка')], max_length=10)),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('club', models.CharField(blank=True, max_length=200)),
                ('trainer', models.ForeignKey(limit_choices_to={'profile__role': 'trainer'}, on_delete=django.db.models.deletion.CASCADE, related_name='athletes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TournamentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age_min', models.PositiveIntegerField()),
                ('age_max', models.PositiveIntegerField()),
                ('weight_max', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gender', models.CharField(choices=[('male', 'Мальчики'), ('female', 'Девочки'), ('any', 'Любые')], default='any', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('athletes', models.ManyToManyField(blank=True, related_name='tournament_categories', to='tournament.athlete')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tournament.tournament')),
            ],
            options={
                'ordering': ['tournament', 'order'],
                'unique_together': {('tournament', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='tournament.tournamentcategory')),
            ],
            options={
                'ordering': ['category', 'order'],
                'unique_together': {('category', 'order')},
            },
        ),
        migrations.CreateModel(
            name='ParentChildLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='tournament.athlete')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('parent', 'athlete')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_number', models.PositiveIntegerField()),
                ('score1', models.PositiveIntegerField(default=0)),
                ('score2', models.PositiveIntegerField(default=0)),
                ('fight_number', models.PositiveIntegerField(default=0)),
                ('scheduled_time', models.DateTimeField(blank=True, null=True)),
                ('round_number', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Ожидается'), ('in_progress', 'Бой идёт'), ('finished', 'Завершён')], default='pending', max_length=20)),
                ('athlete1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_athlete1', to='tournament.athlete')),
                ('athlete2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_as_athlete2', to='tournament.athlete')),
                ('previous_match1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_matches_as_first', to='tournament.match')),
                ('previous_match2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_matches_as_second', to='tournament.match')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_matches', to='tournament.athlete')),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournament.round')),
                ('tatami', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournament.tatami')),
            ],
            options={
                'ordering': ['round__order', 'match_number'],
                'unique_together': {('round', 'match_number')},
            },
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournament.athlete')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournament.tournament')),
            ],
            options={
                'unique_together': {('tournament', 'athlete')},
            },
        ),
    ]
