# Generated by Django 6.1 on 2026-08-31 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидается'), ('ready', 'Готов'), ('in_progress', 'Бой идёт'), ('finished', 'Завершён'), ('bye', 'Автопроход')], default='waiting', max_length=20),
        ),
    ]
