# Generated by Django 6.1 on 2026-09-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_tournament_created_by_alter_match_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
