# Generated by Django 6.1 on 2026-09-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_match_end_time_match_start_time_tournament_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
