# Generated by Django 6.1 on 2026-09-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_tournament_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='accumulated_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидает'), ('in_progress', 'Идёт'), ('finished', 'Завершён')], default='waiting', max_length=20),
        ),
        migrations.AddField(
            model_name='tournamentcategory',
            name='match_duration',
            field=models.PositiveIntegerField(default=120),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидается'), ('ready', 'Готов'), ('in_progress', 'Бой идёт'), ('paused', 'Пауза'), ('finished', 'Завершён'), ('bye', 'Автопроход')], default='waiting', max_length=20),
        ),
    ]
