# Generated by Django 6.1 on 2026-09-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_match_accumulated_seconds_match_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='link_code',
            field=models.CharField(blank=True, default='', max_length=12),
        ),
    ]
