# Generated by Django 6.1 on 2026-09-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_athlete_link_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='link_code',
            field=models.CharField(blank=True, default=None, max_length=12, null=True),
        ),
        # Пустые строки не участвуют в unique-ограничении только как NULL.
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model("tournament", "Athlete")
            .objects.filter(link_code="")
            .update(link_code=None),
            reverse_code=migrations.RunPython.noop,
        ),
    ]
