# Generated by Django 6.1 on 2026-09-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_alter_athlete_link_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='link_code',
            field=models.CharField(blank=True, default=None, max_length=12, null=True, unique=True),
        ),
    ]
