# Generated by Django 6.1 on 2026-09-06 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_alter_athlete_link_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('start', 'Старт'), ('pause', 'Пауза'), ('resume', 'Продолжение'), ('finish', 'Финиш'), ('reopen', 'Переоткрытие'), ('tatami', 'Назначение татами')], max_length=20)),
                ('score1', models.PositiveIntegerField(blank=True, null=True)),
                ('score2', models.PositiveIntegerField(blank=True, null=True)),
                ('detail', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_actions', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='action_logs', to='tournament.match')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logged_wins', to='tournament.athlete')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
    ]
