# Generated by Django 6.1 on 2026-09-06 17:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_matchactionlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('match.started', 'Бой стартовал'), ('match.paused', 'Бой на паузе'), ('match.resumed', 'Бой продолжен'), ('match.finished', 'Бой завершён'), ('match.reopened', 'Бой переоткрыт'), ('match.tatami', 'Татами назначено'), ('round.started', 'Раунд стартовал'), ('round.finished', 'Раунд завершён'), ('category.members', 'Состав категории'), ('category.bracket', 'Сетка построена'), ('tournament.updated', 'Турнир обновлён')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_events', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='tournament.tournamentcategory')),
                ('match', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='tournament.match')),
                ('round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_events', to='tournament.round')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tournament.tournament')),
            ],
            options={
                'ordering': ['id'],
                'indexes': [models.Index(fields=['tournament', 'id'], name='tournament__tournam_823ef8_idx')],
            },
        ),
    ]
