# Generated by Django 6.1 on 2026-09-08 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_tournamentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentcategory',
            name='tatami',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='tournament.tatami'),
        ),
    ]
