# Generated by Django 6.1.1 on 2026-09-10 11:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_tournamentcategory_tatami'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='link_code',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tournamentcategory',
            name='match_duration',
            field=models.PositiveIntegerField(default=120, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='tournamentcategory',
            name='weight_max',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
